ame: Deploy Contracts

on:
  push:
    branches: [main]
    paths:
      - 'apps/web3-core/contracts/**'
      - 'apps/web3-core/deploy/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build contracts
        run: |
          cd apps/web3-core
          pnpm run compile
          
      - name: Run tests
        run: |
          cd apps/web3-core
          pnpm run test
          
      - name: Deploy to mainnet
        if: github.ref == 'refs/heads/main'
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        run: |
          cd apps/web3-core
          pnpm hardhat deploy --network mainnet
          
      - name: Update SDK
        run: |
          pnpm run build --filter @cryptiq/web3-sdk
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'chore: update contract addresses'
          commit-message: 'chore: update contract addresses'
          branch: 'chore/update-addresses'
          base: main