services:
  cryptiq-shell:
    build:
      context: ./apps/cryptiq-shell
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/cryptiq-shell:/app
      - /app/node_modules

  wallet-service:
    build:
      context: ./services/wallet-service
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    environment:
      - NODE_ENV=development
    env_file:
      - ./services/wallet-service/.env
    volumes:
      - ./services/wallet-service:/app

  portfolio-service:
    build:
      context: ./services/portfolio
      dockerfile: Dockerfile
    ports:
      - '5003:5003'
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/portfolio/.env
    volumes:
      - ./services/portfolio:/app

  agent-monitor-service:
    build:
      context: ./services/agent-monitor-service
      dockerfile: Dockerfile
    ports:
      - '5004:5004'
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/agent-monitor-service/.env
    volumes:
      - ./services/agent-monitor-service:/app

  ai-assistant:
    build:
      context: ./services/ai_assistant
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/ai_assistant/.env
    volumes:
      - ./services/ai_assistant:/app

  # Example for AI Market Analysis Service
  market-analysis-service:
    build:
      context: ./services/market/analysis
      dockerfile: Dockerfile
    ports:
      - '5006:5006'
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/market/analysis/.env
    volumes:
      - ./services/market/analysis:/app
